In [12]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [13]:
ds=pd.read_csv(r"C:\Users\arunf\OneDrive\Documents\Data Science\Machine Learning\DataSet\iris (4).csv")

In [14]:
ds

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [15]:
ds.isnull().sum()

Sepal.Length    0
Sepal.Width     0
Petal.Length    0
Petal.Width     0
Species         0
dtype: int64

In [16]:
train,test=train_test_split(ds,test_size=0.2)

In [17]:
trainx=train.iloc[:,:4]
trainy=train.iloc[:,4]
testx=test.iloc[:,:4]
testy=test.iloc[:,4]

In [19]:
trainx

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
80            5.5          2.4           3.8          1.1
149           5.9          3.0           5.1          1.8
30            4.8          3.1           1.6          0.2
20            5.4          3.4           1.7          0.2
91            6.1          3.0           4.6          1.4
..            ...          ...           ...          ...
134           6.1          2.6           5.6          1.4
78            6.0          2.9           4.5          1.5
28            5.2          3.4           1.4          0.2
145           6.7          3.0           5.2          2.3
44            5.1          3.8           1.9          0.4

[120 rows x 4 columns]

In [18]:
trainy

80     versicolor
149     virginica
30         setosa
20         setosa
91     versicolor
          ...    
134     virginica
78     versicolor
28         setosa
145     virginica
44         setosa
Name: Species, Length: 120, dtype: object

In [20]:
gnb=GaussianNB()
mnb=MultinomialNB()
bnb=BernoulliNB()

In [21]:
pred_gnb=gnb.fit(trainx,trainy).predict(testx)
pred_mnb=mnb.fit(trainx,trainy).predict(testx)
pred_bnb=bnb.fit(trainx,trainy).predict(testx)

In [22]:
cm1=confusion_matrix(pred_gnb,testy)
accgnb=np.mean(pred_gnb==testy.values.flatten())

In [23]:
cm1

array([[ 7,  0,  0],
       [ 0,  9,  0],
       [ 0,  1, 13]], dtype=int64)

In [24]:
mean=(7+9+13)/(7+9+13+1)
mean

0.9666666666666667

In [25]:
accgnb

0.9666666666666667

In [27]:
cm2=confusion_matrix(pred_mnb,testy)
accmnb=np.mean(pred_mnb==testy.values.flatten())

In [28]:
cm2

array([[ 7,  0,  0],
       [ 0, 10,  4],
       [ 0,  0,  9]], dtype=int64)

In [29]:
mean=(7+10+9)/(7+10+9+4)
mean

0.8666666666666667

In [30]:
accmnb

0.8666666666666667

In [31]:
cm3=confusion_matrix(pred_bnb,testy)
accbnb=np.mean(pred_bnb==testy.values.flatten())

In [32]:
cm3

array([[ 7, 10, 13],
       [ 0,  0,  0],
       [ 0,  0,  0]], dtype=int64)

In [33]:
mean=(7)/(7+10+13)
mean

0.23333333333333334

In [34]:
accbnb

0.23333333333333334